= RMANBackupsReport
Norman Dunbar <norman.dunbar@hermes-europe.co.uk> 
v1.0, 2018-04-07
:doctype: book
:media: prepress
:toc: left
:toclevel: 4
:icons: font
:!sectnums:
:source-highlighter: coderay

== RMANBackupsReport

This is a test application to use the OCILIB Oracle database access
tools from https://github.com/vrogier/ocilib on Windows and Linux. It
seems to work!

The application itself requires that OCILIB's lib directory and the
ORACLE_HOME/lib directory have been installed on PATH and/or
LD_LIBRARY_PATH.

The application logs in to a database (or some databases) and reports
back on the list of RMAN backups that have taken place since
_some days ago_ - which it does as the `DBA_USER` account, you can edit
this in `rmanBackups.c` if you need to change it.

=== Compiling

A couple of build scripts are supplied. `Build.cmd` for Windows and `build.sh` for Linux. These are well commented and detail the requirements for the build. However, briefly:

* Make sure that OCILIB is installed and on `%PATH%` or `$LD_LIBRARY_LIST`.
* Edit `build.cmd` (Windows) or `build.sh` (Linux) and change the various settings to suit where you have installed OCILIB, Oracle Client etc. 
* On Linux, make sure `LIBPATH` is correct for your `$ORACLE_HOME` - we need that in `LD_LIBRARY_PATH` at compile time.
* Save the file(s) and execute them as per your system.

=== Execution

Once you have a compiled version of the software, probably called
`rmanBackupsReport` or `rmanBackupsReport.exe`, you can run it with the
following command line parameters:

* a list of space separated database alias names as per your client's
`tnsnames.ora` file. Double quotes can be used around any of the alias
names if there are _interesting_ characters in the name, etc.
* The password for a used, defaulting to `dba_user` (yes, I _know_, I
should have passed it on the command line, but that's not how _my_
system is set up, and I'm lazy, ok!) - but you can change the default
account in the file `rmanBackups.c` as mentioned above.
+
It is assumed, because my systems does it, that all the databases in the
list, will use the same account and password. You may need to run the
report separately if this is different at your installation. It's only
a test application after all!
* The number of days ago you wish to look back at the RMAN backups for.
1, for example, will give you everything from yesterday plus anything
from today, up until now. (In other words, it's not just the backups
taken on those numbers of days, but always includes anything up to now.)

For example:

[source,bash]
----
./rmanBackupsReport db_one db_two db_three secret_password_string 3
----

==== Warnings on Execution

You may see the following warning when executing the application, it can
be happily ignored:

[source,none]
----
Checking database ORCL
ORA-24347: Warning of a NULL column in an aggregate function
Error ORA-24347 detected
Checking complete.
----

It is just a warning and in this case, we don't care.

=== Output Report Files

The application produces n HTML report on stdout, so you should redirect
that to a file if you want to capture the report data. For example:

[source,bash]
----
./rmanBackupsReport db_one db_two db_three secret_password_string 3 >rmanReport.html
----

You also can, if you wish, redirect stderr to a log file so that any
errors are logged and not just displayed on screen.

[source,bash]
----
./rmanBackupsReport db_one db_two db_three secret_password_string 3 >rmanReport.html 2>rmanReportErrors.log
----

Easy or what?

Norman Dunbar May 2018.
