= RMANBackupsReport
Norman Dunbar <norman.dunbar@hermes-europe.co.uk> 
v1.1, 2019-07-03
//v1.0, 2018-04-07  // Original version

:doctype: book
:media: prepress
:toc: left
:toclevel: 4
:icons: font
:!sectnums:
:source-highlighter: coderay

== RMANBackupsReport

This is a test application to use the OCILIB Oracle database access tools from https://github.com/vrogier/ocilib on Windows and Linux. It seems to work!

The application itself requires that OCILIB's lib directory and the `ORACLE_HOME/lib` directory have been installed on `PATH` and/or `LD_LIBRARY_PATH`.

The application logs in to a database (or some databases) and reports back on the list of RMAN backup jobs that have taken place since _some days ago_.


=== Compiling

A couple of build scripts are supplied. `Build.cmd` for Windows and `build.sh` for Linux. These are well commented and detail the requirements for the build. However, briefly:

* Make sure that OCILIB is installed and on `%PATH%` or `$LD_LIBRARY_LIST`.
* Edit `build.cmd` (Windows) or `build.sh` (Linux) and change the various settings to suit where you have installed OCILIB, Oracle Client etc. 
* On Linux, make sure `LIBPATH` is correct for your `$ORACLE_HOME` - we need that in `LD_LIBRARY_PATH` at compile time.
* Save the file(s) and execute them as per your system.

=== Execution

Once you have a compiled version of the software, probably called `rmanBackupsReport` or `rmanBackupsReport.exe`, you can run it with the single command line parameter naming a file which contains Oracle logion details as described in the 'UserGuide'.

For example:

[source,bash]
----
./rmanBackupsReport logons.txt
----

==== Warnings on Execution

You may see the following warning when executing the application, it can be happily ignored:

[source,none]
----
Checking database ORCL
ORA-24347: Warning of a NULL column in an aggregate function
Error ORA-24347 detected
Checking complete.
----

It is just a warning and in this case, we don't care.

=== Output Report Files

The application produces an HTML report on stdout, so you should redirect that to a file if you want to capture the report data. For example:

[source,bash]
----
./rmanBackupsReport logons.txt >rmanReport.html
----

You also can, if you wish, redirect stderr to a log file so that any errors are logged and not just displayed on screen.

[source,bash]
----
./rmanBackupsReport logons.txt >rmanReport.html 2>rmanReportErrors.log
----

Easy or what?

Norman Dunbar July 2019.
